### ISSUE TITLE
Can't resolve typechain AGIMigrationWrapAdapter

### ISSUE THREAD

**Issue by rootulp** [SetProtocol/set-protocol-v2#143]
I'm attempting to use master of this package from index-ui via `yarn link`. I've built set-protocol-v2 successfully. However, when I start the React dev server in index-ui, I observe:

```
../set-protocol-v2/dist/utils/contracts/index.js
Module not found: Can't resolve '../../typechain/AGIMigrationWrapAdapter' in '/Users/rootulp/git/index-coop/set-protocol-v2/dist/utils/contracts'
```

It appears the requested file is actually one directory above where it is being searched for in `dist`.

```
~/git/index-coop/set-protocol-v2/dist/utils/contracts on master ····················································
❯ ls
aave.js           axieInfinity.js   compound.js       index.js          singularityNet.js uniswapV3.js
aaveV2.js         balancer.js       curve.js          kyberV3.js        uniswap.js        yearn.js

~/git/index-coop/set-protocol-v2/dist/utils/contracts on master ····················································
❯ ls ../../typechain
commons.js factories  index.js

~/git/index-coop/set-protocol-v2/dist/utils/contracts on master ····················································
❯ ls ../../../typechain
AGIMigrationWrapAdapter.d.ts                  IPriceOracle.d.ts
... <rest of output truncated>
```

However, in the original source, the line that defines this correctly resolves type definitions because `set-protocol-v2/typechain/AGIMigrationWrapAdapter.d.ts` exists
https://github.com/SetProtocol/set-protocol-v2/blob/a80eb4cedd5c6e32e67ab492fd169afd462a82a3/utils/contracts/index.ts#L15-L15

So it looks like something funky is happening in the packaging of `dist`. Apologizes if this issue only occurs during development time and would go away if I added a dependency on `set-protocol-v2` once a release is cut

**Comment by cgewecke** [comment]
Yes, this is a breaking change [in the release (0.1.0)][1]. These ambient `d.ts` types are no longer transpiled and bundled with the `dist`.  

Instead you import them from a typechain folder included in the outer layer of the package.
```ts
import { Controller } from "@setprotocol/set-protocol-v2/typechain"
```

Does that pattern work for index-ui? 

[1]: https://github.com/SetProtocol/set-protocol-v2/releases/tag/0.1.0

**Comment by cgewecke** [comment]
There's a relevant issue about this at [typechain 430][1]

[1]: https://github.com/dethcrypto/TypeChain/issues/430

**Comment by rootulp** [comment]
I really appreciate the links and release notes, thanks for sharing! index-ui doesn't directly depend on any types from set-protocol-v2. Instead it takes a direct dependency on `set.js`. So I don't think we should be impacted by the ambient type location move. Is it possible that this problem is unique to the `set-protocol-v2/dist/utils/contracts/index.js` and would repro if set-protocol-v2 was used as a lib in any other context?

**Comment by cgewecke** [comment]
> Is it possible that this problem is unique to the set-protocol-v2/dist/utils/contracts/index.js and would repro if set-protocol-v2 was used as a lib in any other context

Yes, perhaps we could add some notes about our typechain distribution to the README.  

I *think* including the folder as a non-dist asset is conventional in ethereum typechain projects atm...(saw that suggestion over there a while ago)

Ultimately, set.js consumes them this way in [set.js PR 76][1] and looks like everything works. 

[1]: https://github.com/SetProtocol/set.js/pull/76

**Comment by rootulp** [comment]
Disregard my earlier comment. https://github.com/SetProtocol/set.js/pull/76 appears to resolve the issue I was encountering because when I build that PR locally, set.js is able to resolve the types in set-protocol-v2. Given the breaking change was called out in https://github.com/SetProtocol/set-protocol-v2/releases/tag/0.1.0, I'm comfortable closing this. Thanks for all of your help!
